name: Unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup zig
        uses: goto-bus-stop/setup-zig@v2
        with: 
          version: 0.12.0
      - run: zig test src/tacGenTests.zig &&  zig test src/semanticTests.zig && zig test src/codegenTests.zig  && zig test src/parserTests.zig && zig test src/staticStorageTests.zig
      - run: cd cFiles && sh test.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - run: zig fmt --check .
